#!/bin/sh
set -eu

: "${T3CODE_HOME:?Missing app-owned data directory}"
: "${T3CODE_FLATPAK_SERVER:?Missing bundled server executable}"
: "${T3CODE_FLATPAK_ENTRY:?Missing bundled server entry point}"
unset NODE_OPTIONS NODE_PATH
unset T3CODE_PORT T3CODE_MODE T3CODE_NO_BROWSER T3CODE_HOST
unset T3CODE_DESKTOP_WS_URL T3CODE_DESKTOP_LAN_ACCESS T3CODE_DESKTOP_LAN_HOST
unset T3CODE_DESKTOP_HTTPS_ENDPOINTS T3CODE_TAILSCALE_SERVE T3CODE_TAILSCALE_SERVE_PORT
cd "$HOME"

export ELECTRON_RUN_AS_NODE=1
exec "$T3CODE_FLATPAK_SERVER" "$T3CODE_FLATPAK_ENTRY" --bootstrap-fd 3
